name: ice_line_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  device_preview: 1.3.1
  dio: ^5.7.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  json_annotation: ^4.9.0
  percent_indicator: ^4.2.5
  provider: ^6.1.5
  retrofit: 4.7.3
  shared_preferences: ^2.5.4
  table_calendar: ^3.2.0


dev_dependencies:
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  very_good_analysis: ^10.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.jpg"
  adaptive_icon_background: "#FFFFFF00"
  adaptive_icon_foreground: "assets/icons/icon.jpg"
